### ISSUE TITLE
Besoin d'un CMS pour les assos de l'UCP

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#1]
Les associations on besoin d'un CMS pour gérer leur site.
On utilisera cette issue pour lister les issues utiles à garder en mémoire.
- [Principes](./2)
- [Guide de style](./3)

**Comment by Uinelj** [comment]
Peut-être qu'une milestone serait plus adaptée ?

**Comment by akkes** [comment]
Pas vraiment. Mais un wiki ou seulement un label oui.
