### ISSUE TITLE
modèle de données

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#11]
Vu qu'on a une petite idée des fonctionnalités qu'on va implémenter, j'ai fait un mld.

[moussaillon-mld.pdf](https://github.com/Moussaillons/Moussaillon/files/376709/moussaillon-mld.pdf)
- Chaque association a un projet "par défaut" qui désigne tout les éléments qui ne sont pas dans un projet. (dont il nous faut trouver le nom)
- les posts référencent l'URI des fichiers pour les inclure

Version éditable sur [draw.io](draw.io) (si vous avez mieux ;-)): [moussaillon-mld.txt](https://github.com/Moussaillons/Moussaillon/files/376713/moussaillon-mld.txt)

**Comment by Uinelj** [comment]
Du coup on utilise une database ?

**Comment by akkes** [comment]
Yep, tu voulais faire ça avec des fichiers textes?

**Comment by Uinelj** [comment]
Non mais il va falloir choisir un sgbd :)

**Comment by akkes** [comment]
Il me semble que tu t'y connais mieux en db que moi? J'aimerai bien avoir ton avis avant histoire de ne pas t'influencer

**Comment by Uinelj** [comment]
Haha ! Honnêtement tout irait je pense. 
Vu qu'on a des histoires de pk/fk, ça serait cohérent de prendre un sgbdr.

Après, python/flask va bien avec certains "ORM" (j'ai pas regardé la signification du terme), voir ce [lien](https://www.fullstackpython.com/object-relational-mappers-orms.html).

Edit: Il semblerait qu'un ORM te permet de stocker "seamlessly" des objets dans une db sans t'emmerder avec le côté relationnel.

**Comment by akkes** [comment]
J'allais dire que la question était de savoir si on prend un truc comme SQLAlchemy. Mais tu pose déjà la question! 😄

_afaik:_
- pgsql est le sgdb habituel pour python
- Il scale mieux que MariaDB
- Il respecte mieux les standards SQL

On pourrai prendre sqlite en local pour pas avoir pgsql à installer si ça arrange?

J'ai utilisé un modèle relationnel parce que:
- les db NoSQL sont pas encore proposé en standard dans les offres d'hébergment
- Je connais pas assez les modèles NoSQL pour les utiliser.

**Comment by Uinelj** [comment]
Je suis ok pour une db ORM + sqlite. On pourra scale sur du pgsql assez facilement après de toute façon, non ?

Edit : On choisit quoi comme ORM ? SQLAlchemy ? Peewee ? J'ai cru voir pas mal de gens qui utilisaient peewee + flask.
