### ISSUE TITLE
<Resolu> Défaut d'installation

### ISSUE THREAD

**Issue by Eresia** [Moussaillons/Moussaillon#12]
Petite issue pour remonter les défauts liés à l'installation.
Ici pas vraiment un bug, mais je ne sais pas si mettre un truc dans le bashrc est une bonne idée. Tout le monde n'est pas sur bash ^^"

**Comment by Eresia** [comment]
Et d'ailleurs je n'ai aucunement de /usr/local/bin/virtualenvwrapper.sh

**Comment by Eresia** [comment]
Et quand je veux source le .sh, je me tape un : 

`/usr/bin/python: No module named virtualenvwrapper
virtualenvwrapper.sh: There was a problem running the initialization hooks. 

If Python could not import the module virtualenvwrapper.hook_loader,
check that virtualenvwrapper has been installed for
VIRTUALENVWRAPPER_PYTHON=/usr/bin/python and that PATH is
set properly.`

**Comment by akkes** [comment]
Si t'es assez grand pour modifier ton shell, n'es-tu pas assez grand pour adapter un script d'install? Surtout qu'on ne paste pas un script dans un terminal sans le comprendre. Par contre c'est vrai qu'on devrait commenter pour faciliter la compréhension et donc l'adaptabilité du script.

Pour Python qui ne trouve pas virtualenvwrapper: l'erreur ne vennant pas, jusqu'à preuve du contraire, de moussaillon il ne me semble pas que l'on ai quelque chose à corriger. Je te renvoie à [la docummentation de virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/) pour chercher une solution. Par contre je serai heureux de pouvoir t'aider en off.

**Comment by Eresia** [comment]
Tu es sans doute assez grand, mais devoir modifier son bashrc pour installer un programme, est ce une bonne pratique ?

**Comment by akkes** [comment]
Le programme en question touchant à des variables d'environnement c'est surtout la seule solution que je connaisse! [La docummentation de virtualenvwrapper demande bien](https://virtualenvwrapper.readthedocs.io/en/latest/install.html#shell-startup-file) de le faire

**Comment by Eresia** [comment]
Ouai...

Bon, pour ceux qui aurait eu mon problème, faut faire "VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3"

C'est juste que /usr/bin/python c'est pas forcément python3 par défaut...

**Comment by Eresia** [comment]
Si certain on l'erreur `ERROR: virtualenvwrapper could not find virtualenv in your path`, ajouter `export PATH="$HOME/.local/bin:$PATH"` dans votre ~/.profile
