### ISSUE TITLE
Guide de style

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#3]
## Python
- [PEP8](https://www.python.org/dev/peps/pep-0008/)
- [PEP257](https://www.python.org/dev/peps/pep-0257/)

([un résumé des deux](http://docs.python-guide.org/en/latest/writing/style/) est disponible)
## CSS

TODO: À définir
## HTML

TODO: À définir

**Comment by Uinelj** [comment]
J'aimerais rajouter que pour checker son code il existe un site pas mal du tout : [pep8online](http://pep8online.com/), et une lib python [flake8](http://flake8.pycqa.org/en/latest/).

**Comment by akkes** [comment]
Pensez à utiliser un linter (ou à changer d'éditeur de code)
