### ISSUE TITLE
Définir l'usage

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#4]
Ça serai cool qu'on définisse où on s'arrête pour la première release.

**Comment by akkes** [comment]
je propose qu'on s'arrête sur les fonctionnalités propres aux sites internets pour la R1.
Voici [les mockups](https://github.com/Moussaillons/Moussaillon/files/366173/moussaillon.pdf) pour voir à quoi ça pourrai ressembler

**Comment by Eresia** [comment]
Qu'est ce que tu penses qui peut être réalisable ?

**Comment by akkes** [comment]
Tout! À condition d'y mettre le temps ;-)

**Comment by Eresia** [comment]
Ok ! Je commence la création de la fusée UCP
