### ISSUE TITLE
Définir les URL

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#5]
Vu qu'on a une idée de la structure (cf. #4 ) ce serai cool qu'on définisse le format des urls pour la 0.1.

Je propose que:
- Chaque asso ai son sous-domaine. Ex: hazybot.federationucp.fr
- L'administration se fait sur le site parent. Ex: federationucp.fr
- le dashboard soit à la racine. Ex: federationucp.fr/
- les posts sur /posts/.
- l'édition d'un post se fasse sur /posts/nom-du-post. L'ajout sur /posts/new
- La galerie sur /gallery/
- L'upload sur /gallery/upload
- Le calendrier sur /calendar/
- L'ajout d'évènement sur /calendar/add
- Le login sur /login

**Comment by akkes** [comment]
on devrait pas mettre tout ça dans un /panel pour pouvoir évoluer et avoir une vue publique par la suite?

**Comment by Uinelj** [comment]
L'URL sera vraiment federationucp.fr ?

**Comment by Uinelj** [comment]
Je suis assez hésitant sur l'administration sur le nom de domaine. Je ne suis pas expert, mais perso je préfèrerais avoir `echo.fedeucp.fr/admin` plutôt que d'avoir `fedeucp.fr/admin`, ça me permet d'avoir une URL unique par panel d'admin.

**Comment by akkes** [comment]
Pour fédérationucp.fr je prend ça juste en exemple. Y'a eu absolument aucune discussion, même informelle, sur le sujet.

Si j'ai mit l'administration sur le domaine racine c'est pour permettre d'avoir un compte unique pour toutes les assos pour les personnes étant dans plusieurs assos. Sur les mockups on pourrai switcher avec un menu déroulant en haut de la sidebar (au niveau du nom de l'asso). Mais le problème que tu pointe est important.

**Comment by Uinelj** [comment]
C'est vraiment un choix, au final. Je sais pas si l'URL rewriting gère les sous domaines aussi, mais si c'est le cas, c'est trivial à implémenter.
C'est surtout au niveau du sens, je trouve ! Et puis les non-tech trouveraient peut-être plus de sens à avoir une page d'administration par association.

Mais encore une fois, je ne suis pas expert.

**Comment by akkes** [comment]
En gros on peut faire les URL comme on veut. À terme ça devrai supporter les NDD personnalisés (versitylan.com)
Mais c'est vrai que hormis du coté de chez Hazybot/Echo pas beaucoup de monde doit être dans plusieurs assos. Perso je valide le fait de passer le panel dans le sous domaine de l'asso. J'invite les gens du chat à venir en discuter.

**Comment by Eresia** [comment]
Au pire tu peux faire un "panel de gestion par assoc" mais qui ne serait finalement qu'une redirection caché vers le panel de gestion général. Et du coups c'est invisible mais permet quand même de pouvoir gérer plusieurs asso en même temps (rien que pour les admin par exemple)

Au pire tu fais juste qu'il pointe par défaut vers l'assoc sélectionnée

**Comment by Uinelj** [comment]
Je veux bien un exemple avec des faux liens @Eresia , j'ai pas tout saisi.

**Comment by Eresia** [comment]
Bah tout simplement que l'adresse "echo.fedeucp.fr/admin" renvoi de manière transparente vers "fedeucp.fr/admin" mais directement sur l'onglet "Echo"

(Entre parenthèse, je suis contre fedeucp.fr, je ne veux pas être dépendant d'eux. Oui je sais c'est juste un exemple :p)

**Comment by Uinelj** [comment]
Ah, qu'en d'autres termes t'aie une redirection !
Honnêtement les deux me vont, c'est juste que `echo.foobar.com/admin` ça détache ton asso du CMS, ce qui, je pense, sera bien mieux perçu par les admins des autres asso.
Ça fait moins "je suis sur un site qui n'est pas à moi et qui gère mon asso", et plus "j'ai pris un hébergement sur un site, et j'ai mon petit espace à moi", à la manière d'un blog, plus que d'un subreddit.

**Comment by akkes** [comment]
Ce dont vous parlez n'est pas un redirect mais un alias. C'est simple à faire mais niveau ergo c'est dégueu (comment on sait quel est le lien canonique?).

Le débat est juste sur l'URL. Le switch entre les panels est faisable en mettant le panel dans le sous-domaine. (et ça permettrait probablement de simplifier du code aussi)

@Eresia en même temps, tout le pitch c'est que la fédé gère l'hébergement pour les asso. Donc t'aura forcément un truc qui y fait référence dans le NDD racine. À terme par contre on supportera les NDD personnalisés.

**Comment by Eresia** [comment]
Dac. Bah du coups plutôt blabla.fr/admin alors

Et @akkes où est ce que tu a vu que c'est la fédé qui hébergera ? Pour moi c'est la fac. Je vois plutôt un truc comme associations.u-cergy.fr

**Comment by akkes** [comment]
Quand on gèrera les domaines personnalisés. ;-)

On a présenté le concept à la fédé, pas à la fac. D'où le fait que je l'utilise comme exemple. Mais ce n'est qu'une supposition. D'un autre coté je ne suis pas sur que la fac accepte de l'héberger.

**Comment by Eresia** [comment]
Tkt, Renier j'en fait mon affaire :]

**Comment by Uinelj** [comment]
J'en ai parlé informellement à Adel(i/è)ne, de la vie culturelle/associative, qui était super intéressée par le projet :)

**Comment by Eresia** [comment]
La vie assoc n'est pas au courant ? J'avais demandé à la fédé de transmettre pourtant :(
