### ISSUE TITLE
Besoin d'une chartre graphique

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#6]
Pour les mockups (cf. #4 ) j'ai utilisé [Tomorrow](https://github.com/ChrisKempson/Tomorrow-Theme).

Ce serai cool qu'on ai une chartre en cohérence avec le thème qu'on a eu jusqu'à présent.

**Comment by Eresia** [comment]
Tu veux prendre une chartre général pour Moussaillon ou que chaque instance puisse avoir la sienne ? Et dans le deuxième cas, est ce qu'on prend celle de la fac ou une autre ? (Ou une amélioration de celle de la fac)

**Comment by Uinelj** [comment]
Amha chaque association devrait pouvoir avoir sa charte graphique, et pour le site "global" on devrai reprendre celle de l'Université ou celle que la vie associative utilise.

**Comment by Eresia** [comment]
Oui pour chaque assoc je suis d'accord, c'était pour le global que je disait.

La vie associative reprend celle de la fac

**Comment by akkes** [comment]
Je parlais d'une charte graphique pour l'administration. Au début on prend la même dans tout le panel. Éventuellement, à terme, un choix du color scheme (voire un CSS?) à la Slack.

Tout le reste devra utiliser des templates (jinja2) modifiables. Je pense en proposer (~6) en exemple. Si possibles avec des couleurs modifiables, à la DotClear, pour ceux qui ne peuvent par faire un design propre pour leur asso.

**Comment by Uinelj** [comment]
Nice !

On pourrait, à la limite, proposer des "couleurs d'association" à la création de l'asso, ce qui permettrait de construire un pseudothème dessus.
