### ISSUE TITLE
Nommer les release

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#7]
Je sais pas si vous connaissez la tradition de donner des noms aux versions de logiciels. Ce serai cool qu'on le fasse.

On pourrai nommer selon:
- Les pirates célèbres
- Les navires célèbres

**Comment by Uinelj** [comment]
Je vote pour les pirates. On pourrait commencer par trouver un pirate un peu clunky pour la premiere release, vu que ça va être assez rudimentaire.

**Comment by akkes** [comment]
On prend aussi dans les pirates fictifs ou seulement les pirates réels?

**Comment by Uinelj** [comment]
Amha on peut prendre les deux.

**Comment by Eresia** [comment]
Pirate + Corsaire ? (Je veux ma version Surcouf)

**Comment by akkes** [comment]
Les corsaires aussi avaient des moussaillons, pourquoi pas!
