### ISSUE TITLE
Tester la mise en place de l'environnement

### ISSUE THREAD

**Issue by akkes** [Moussaillons/Moussaillon#8]
J'ai mis en place la structure de base du projet. Vous pouvez vérifier que ça marche chez vous en suivant le README?

**Comment by Eresia** [comment]
Y a un moyen simple que le truc soit rediriger sur 127.0.0.1/moussaillon au lieu de 127.0.0.1 tout court ? Mon localhost est déjà utilisé

**Comment by Uinelj** [comment]
Bind un autre port sinon ;)

**Comment by Eresia** [comment]
Ton navigateur connaît que le port 80/443 (sans magouille), donc c'est plutôt l'adresse qu'il faut changer ^^

**Comment by Uinelj** [comment]
`http://127.0.0.1:port/moussaillon` devrait fonctionner. C'est comme ça que je query sur Zelkow, le serveur écoute sur 6767. Et quand tu fais un `python -m SimpleHttpServer`, c'est le port 8000 qui est utilisé !

**Comment by Eresia** [comment]
Oui j'ai remarqué que j'ai dit de la grosse merde, c'est juste que le 80 est utilisé par défaut xD

**Comment by akkes** [comment]
Pour l'instant le port par défaut est 5000. Y'a les adresses dans le README pour vous faciliter la tâche. :-)

Du coup ça marche?

**Comment by Uinelj** [comment]
Je vais tester.

Truc pas clair : Tu dis qu'il faudrait adapter si on est sur OSX, et tu mets une liste de commandes. Ce sont des trucs spécifiques OSX, du coup ?

**Comment by akkes** [comment]
Non, ce sont les commandes pour les UNIX potables. Sous OSX j’ai du adapter. Mais je n’ai pas eu l’occasion de tester sous un UNIX potable. D’où ma question.

**Comment by Uinelj** [comment]
Ok.
Pars du `git clone`, si possible aussi, histoire de savoir si on doit pas `cd` à un moment.

**Comment by Uinelj** [comment]
```
(moussaillon) uj Moussaillon master > pip install -r requirements.txt 
Collecting click==6.6 (from -r requirements.txt (line 1))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 921kB/s 
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 1.8MB/s 
Collecting itsdangerous==0.24 (from -r requirements.txt (line 3))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 3.2MB/s 
Collecting Jinja2==2.8 (from -r requirements.txt (line 4))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 1.3MB/s 
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 5))
  Downloading MarkupSafe-0.23.tar.gz
Collecting moussaillon==0.0.1 (from -r requirements.txt (line 6))
  Could not find a version that satisfies the requirement moussaillon==0.0.1 (from -r requirements.txt (line 6)) (from versions: )
No matching distribution found for moussaillon==0.0.1 (from -r requirements.txt (line 6))
(moussaillon) uj Moussaillon master > 

```

**Comment by Uinelj** [comment]
En assumant qu'on a fait un `git clone`, puis qu'on a `cd Moussaillon`, et qu'on a fait l'installation, on doit `cd moussaillon` avant de lancer le serveur. C'est rien mais ça serait cool de le dire aussi ;)

Edit: Mybad, ça change rien ?

Impossible de lancer le serveur du coup, `bash: flask : commande introuvable`. Je suppose que c'est à cause du pip install.

**Comment by Uinelj** [comment]
Fixed en enlevant la ligne `moussaillon==0.0.1` du `requirements.txt`.

`Welcome to website`, ça marche sur Ubuntu 16.04 LTS.

**Comment by akkes** [comment]
`python --version` donne quoi?

**Comment by akkes** [comment]
Tu peux modifier le README en conséquence?

**Comment by Uinelj** [comment]
Je peux que faire des PR :/
Et je crois qu'on peut pas labeliser les issues non plus.

**Comment by akkes** [comment]
Ça devrai être fixé. (Je te laisse tester sur #10
